version: '3.8'

services:
  application:
    build: .
    container_name: perf-test
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - mysql
      - mongo

  mysql:
    image: mysql:8.0
    container_name: perf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  mongo:
    image: mongo:6.0
    container_name: perf-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --wiredTigerCacheSizeGB 2

volumes:
  mysql_data:
  mongo_data:
